Edited xorg.conf so work with new version of raspbian
UCSolarCarTeam/Epsilon-Raspberry pull request #4
Opened 2017-02-24 00:01 UTC by badeniran

Added another device for the second adapter and commented out the primary screen using the pi's onboard graphics.

2017-02-24 00:16 UTC, enochtsang commented
Shit it works? If so really good job baba, I thought I'd be the only one who would be able to do this one :D

2017-10-12 05:25 UTC, bill-luu commented
Nice! I'll merge this when I see it running in person. The readme should be in asciidoc format.

2017-10-12 05:26 UTC, bill-luu requested changes

2017-10-12 05:26 UTC, bill-luu commented on README.md
> +# Epsilon-Raspberry
Team standard is to have the readme as an asciidoc file.

2017-10-18 05:05 UTC, bill-luu approved these changes

2017-10-18 05:33 UTC, merged